### ISSUE TITLE
scale degrees start with 1 not 0

### ISSUE THREAD

**Issue by wolftune** [thuselem/hebdomad#1]
standard music scales always start with 1 not 0, so hebdomad shows that wrongly per convention.

**Comment by bgins** [comment]
I've seen both conventions used. Starting scales at 0 corresponds to the way Scala numbers scales.

Maybe a good solution here is to make the `Deg` button a toggle that switches between the two.

**Comment by bgins** [comment]
I've added a toggle to the `Deg` button. The default behavior is scale degrees start at 1. Selecting the `Deg` a second time shows the zero-based version.
